language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run lint
  - npm run test-coverage
  - npm run test-ci

after_script:
  - ./cc-test-reporter format-coverage -t lcov -o .coverage/coverage-final.json .coverage/lcov.info  # Format coverage
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi  # Upload coverage/codeclimate.json