language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
install:
  - npm install

before_script:
  - bash ./.travis_before.sh type

jobs:
  include:
    - stage: "Normal"
      script: npm run build & \
              npm run lint & \
              npm run test-unit-ci & \
              npm run test-int-ci
    - stage: "Cron Train"
      if: type = cron
      script: npm run build & \
              npm run lint & \
              npm run test-unit-ci & \
              npm run test-int-ci & \
              npm run test-mutate

after_script:
  - ./cc-test-reporter format-coverage -t lcov .coverage/lcov.info
  - ./cc-test-reporter upload-coverage